fastapi
uvicorn[standard]
asyncpg
prometheus-client
pydantic

# OpenTelemetry core
opentelemetry-api
opentelemetry-sdk

# OpenTelemetry exporters
opentelemetry-exporter-otlp

# OpenTelemetry instrumentations
opentelemetry-instrumentation-fastapi
opentelemetry-instrumentation-asgi
opentelemetry-instrumentation-asyncpg
opentelemetry-instrumentation-logging
